### ISSUE TITLE
remove command result

### ISSUE THREAD

**Issue by paolochiodi** [rjrodger/seneca-store-test#15]
specs for the remove command here https://github.com/rjrodger/seneca/blob/master/doc/data-store.md#cmdremove say that the load$ parameter defaults to false, but in the mem-store (which I consider like the reference implementation) it defaults to true.
(also different is the behaviour if all$ is true: no ent is returned)

Which one is correct?

**Comment by rjrodger** [comment]
default load$=false - so only load data if requested with load$=true
all$=true means no data, confirmed
