### ISSUE TITLE
sql support

### ISSUE THREAD

**Issue by paolochiodi** [rjrodger/seneca-store-test#16]
some of the sql stores add some support for sql queries beyond the native$ method: they allow sql strings or an array containing sql string and params as input to the list$ method.

This has also been codified in the tests, but there's no indication of that in the specs. 
Should we keep this functionality? Should it be present among tests?

**Comment by paolochiodi** [comment]
@rjrodger see here for the tests https://github.com/rjrodger/seneca-store-test/blob/master/store-test.js#L457

**Comment by rjrodger** [comment]
no - this is not correct - is not allowed directly :)
a string in this position is always an opaque id

however, we can support { $native:"SELECT..."  } as the query parameter - I think this is a valid use case, as it supports generating entity objects from a native query

note that this feature now applies to all stores, but is OPTIONAL - so we now introduce the idea of optional store features....

frameworks are fun

**Comment by paolochiodi** [comment]
I'm afraid opaque id feature is not mentioned anywhere, I'll add tests for that.

I'll convert the the sql tests to use the native$ option. This will break backward compatibility on some of the stores.

About being optional to some of the stores, seneca-store-test is already constructed in way that makes easy to import and run only relevant tests (e.g.: basics, but not native sql)

**Comment by paolochiodi** [comment]
@rjrodger I was wondering, is the "opaque id" supposed to work with the list$ command too?

**Comment by paolochiodi** [comment]
@rjrodger Additional question: how is { native$: ... } supposed to work?

**Comment by rjrodger** [comment]
list$ should be able to take an array of ids as the query... so a degenerate case is a single id - so yes, opaque ids work for list$ too

{ native$:"SELECT * FROM foo" } should execute the query, and then construct -/-/foo entities using the result set.
