### ISSUE TITLE
ways to test for store errors

### ISSUE THREAD

**Issue by paolochiodi** [rjrodger/seneca-store-test#19]
On issue https://github.com/rjrodger/seneca-store-test/issues/14 we agreed to require errors from the store to be wrapped into seneca specific errors, however I wasn't able to find a smart way to test them (apart the duplicate key error).

The main problem is that there isn't a guaranteed way to agnostically cause an error in the store underling driver. There are three possible path we could follow:
1. require stores to implement "hooks" to trigger errors. I don't like this approach because I don't like to write code just for the sake of testability, and the error would still be "fake-y" when testing
2. require the store implementor to pass in to the tests an additional seneca instance with the store configured in a way that will generate proper errors. I'm afraid this approach will make tests more obscure and complex and may discourage people from using seneca-store-test.
3. don't bother enforcing correct error behaviour in seneca-store-test. At a minimum we could provide a list of "assertion methods" to assert that the error has been properly created for a specific case and leave to the store implementor to use that (something along the lines of "assertValidConnectionError(err)" and "assertValidTimeoutError(err)"). 
Those assertions should check for the correct error code and format

@rjrodger @geek what do you think?

**Comment by geek** [comment]
@paolochiodi what solution do you like best?

**Comment by paolochiodi** [comment]
@geek I prefer 3. I think we'll benefit more from a simple test suite that everyone use than an obscure one that people may not use.
We may catch this kind of problems during reviews and make sure everyone wrap errors

**Comment by geek** [comment]
@paolochiodi sounds like a good plan to me.
