### ISSUE TITLE
entity.remove$ and query

### ISSUE THREAD

**Issue by paolochiodi** [rjrodger/seneca-store-test#20]
I noticed that list$ and load$ will ignore the entity on which they are called and only use the passed in query to filter records.

`remove$` however works slightly different: it ignores the original entity and use the query only if passed in. If no query is passed in the entity is used instead:
```js
var foo = seneca.make('foo')
foo.a = '1'
foo.remove({ b: '2' }, function () {
   // removes only where b = 2
})
```
whilst
```js
var foo = seneca.make('foo')
foo.a = '1'
foo.remove(function () {
   // removes where a = 1
})
```

Is this the intended behaviour? 
Should this be replicated on load and list too?

ps: I think this is actually handled at seneca (not store) level

**Comment by rjrodger** [comment]
load$ should work on the current entity - same functionality as remove$ (I guess it means reload to get latest data)
list$ without a query means list everything

**Comment by paolochiodi** [comment]
ok, let me repeat that - just to make sure I understand correctly:
- load$ and remove$ without a query means act on the current entity
- list$ without a query means list everything
- load$, remove$ and list$ with a query ignore the entity and only use the query

Is this correct?

**Comment by rjrodger** [comment]
yes, correct
