### ISSUE TITLE
opaque ids and list$

### ISSUE THREAD

**Issue by paolochiodi** [rjrodger/seneca-store-test#21]
On issue https://github.com/rjrodger/seneca-store-test/issues/16#issuecomment-146823337 you said that list$ should take an array of ids as "opaque ids" and I coded that in the tests.

However I'm now updating the mem-store and noticed that for the same functionality on load$ the id is handled on seneca side (translating a single string into { id: original_string }.

I'd like to know if you prefer to add the same support for this in list$ on seneca side or leave it to the stores to handle such cases

**Comment by rjrodger** [comment]
add it on the seneca side
